@echo off
setlocal EnableExtensions
call "%~dp0config_windows.bat"
for %%S in (%RECOMMENDED_SEEDS%) do (
  call :run_seed %%S
  if errorlevel 1 exit /b 1
)
echo Completed strict J LOSO for seeds %RECOMMENDED_SEEDS%.
exit /b 0

:run_seed
setlocal
set "TEST_PARTICIPANT=J"
set "SEED=%~1"
for %%V in (FOLD_ROOT PROTOCOL_ROOT RUN_ROOT BACKBONE_OUTPUT BACKBONE_CKPT FEATURE_ROOT MODEL_ROOT E2E_ROOT E2E_TIER3_OUTPUT E2E_NODE_SCRATCH_OUTPUT E2E_NODE_TRANSFER_OUTPUT NORMAL_FOLD_SUMMARY_ROOT ALLRUN_BACKBONE_OUTPUT ALLRUN_BACKBONE_CKPT ALLRUN_FEATURE_ROOT ALLRUN_MODEL_ROOT ALLRUN_E2E_ROOT ALLRUN_E2E_TIER3_OUTPUT ALLRUN_E2E_NODE_SCRATCH_OUTPUT ALLRUN_E2E_NODE_TRANSFER_OUTPUT ALLRUN_FOLD_SUMMARY_ROOT TRAIN_SCOPE_COMPARISON_FOLD_ROOT) do set "%%V="
call "%~dp0run_strict_J_one_seed.bat"
exit /b %ERRORLEVEL%
